server:
  port: 9090

#Dubbo
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  config-center:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: 12345
    name: dubbo
  #scan:
    #base-packages: com.ydhy.bank_message.service.impl